### ISSUE TITLE
Documentation plan

### ISSUE THREAD

**Issue by webratte** [kontalk/website#9]
Very often you have answer the same questions.
What do you think about a moderated (because spam) forum?

My hope is, every question will come only once.
And users could help each other.

There could be differently boards.
-technical questions for server
-technical questions for client
and so on
Actually the informations are very spread:
www.kontalk.org, googlegroups, Github, www.kontalk.net

For 'normal' users it's not easy to find out what is already answered and on which website I can find the answer.

That's just a idea. I don't know if it works how I think.

**Comment by daniele-athome** [comment]
Hello Mike,
I know what you mean. It is indeed a lot of yet to be organized information, and so little time to organize it. As an example, #5 still has to be processed (and I'm sorry for that).

I think a forum would be a too much demanding tool to maintain (hosting, moderating, answering, and so on). I think an optimal way of organization documentation is to keep essential information in a single place and possibly version it.

But let's review the current situation.

* kontalk.org: a single presentation web page with links to GitHub, Google Play, F-Droid and kontalk.net
* kontalk.net: single page web site about the network (that is, kontalk.net itself, which is separated from the software project which is hosted at kontalk.org)
* androidclient GitHub wiki: tutorials and help pages for the Android client
* tigase-extension GitHub wiki: tutorials about the new XMPP server part
* specs GitHub wiki: it's a mess in here at the moment, but it should host specifications and documents about the protocol used in the network
* network GitHub wiki: hosts the network keyring and information about the network itself: the list of registered servers, how to join the network

My proposal is the following:

* decide where (GitHub wiki? GitHub pages? I'd prefer a 3rd party tool instead of our own hosting that needs maintenance thus time) and how to host all those information
* organize information in categories (much like described above, but if you or anyone has suggestions they are welcome)
* maybe create some other specific google groups (such as devel, users (of clients), network, and what else?) and link them from the websites and the wiki pages (they are currently not linked from anywhere)
* replace the publicly visible developer Google Play email address with a google group address (we receive too much email only to us)
* have someone to do a minimum maintenance to all of this (do you feel up to the task? :-))

**Comment by webratte** [comment]
I think the website is not the most important thing.

I thought a forum would be a way to reduce the work by answering much mails because users could help each other.

OK more Google Groups. Its just the same like a Forum but Google. I don't like Google :-P
But the truth is, it's easy to maintain.

If you create a few boards (We have to think about what will be sensibly) I think we will someone find were could help to moderate.
Simple things like "Is Version 2.x and Version 3.x is not compatible ?" I could answer ;-)
But more technical things would stay your turn.

But a mail should not be automatic public (if you replace your deveteam adress with a googlegroupadress) Or is it possible instead of a mailadress put a URL (maybe to kontalk.org/contact?

For your deveteam adress you could create a autoresponder like that:
Please first take a look to our Forums. Maybe your question is already answered bla bla bla.............

In playstore you could recommend to look first on the website (kontalk.org)
There should linked all the stuff (with a short description) like googlegroups, kontalk.net github and so on.

I do not know whether I the right one is to be performed around this work.
I can see that all just as a user.
I'm not the technical specialist

That's just a first idea.
Hopfull other people will have much better Ideas.

**Comment by daniele-athome** [comment]
User's point of view is as important as technical point of view. Techs often take stuff for granted and sometimes users understand other users better. That's why everyone should make their contribution :-)

My idea for the google groups:
* kontalk-devel: general development discussions, alpha & beta releases (should be probably splitted into -server, -android, -desktop?)
* kontalk-users: general users discussions about users of the clients (I'd leave just one board in this case to bring all the users together)
* kontalk-network: discussions about Kontalk network management, but this would be closed to a few members actually participating in the network (i.e. it would not be public)

What else do you have in mind?

**Comment by webratte** [comment]
That sounds good so far.
I don't know whether it is important for developer the group to split.
But you know more about that ;-)

I think it's importantly to find all the stuff in one place.
Kontalk.org is the site who is linked in the App and in the Playstore and so it would be a good place to concentrate all important stuff as a "linklist".

Another idea (if there is not too much work)
I would like an Newsletter or a RSS Feed for importantly News like planed Server down time.
I use Kontalk because the privacy an so I don't use "social networks" like Twitter or G+

**Comment by daniele-athome** [comment]
> Kontalk.org is the site who is linked in the App and in the Playstore and so it would be a good place to concentrate all important stuff as a "linklist".

Indeed. I will improve the website to include more contacts and links.
By the way: thanks for sending me that draft, but I'd like to keep the websites to single presentation pages with all the information, and delegate the rest to the wiki. I will come up with something.

**Comment by webratte** [comment]
Your right. The site should be clear structures. Not more then one or two clicks to the information.

**Comment by webratte** [comment]
It seems this task is done. We have a FAQ page and great Forum and IMO it works :-)
